# Generated by Django 4.2.7 on 2023-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_secondry_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secondry_sites',
        ),
        migrations.AddField(
            model_name='user',
            name='ssites',
            field=models.ManyToManyField(blank=True, null=True, related_name='ssites', to='users.site'),
        ),
    ]
