# Generated by Django 4.2.7 on 2023-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_secondry_sites_user_ssites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssites',
            field=models.ManyToManyField(related_name='ssites', to='users.site'),
        ),
    ]
