# Generated by Django 4.2.7 on 2023-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_announcement_target_alter_announcement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
