# Generated by Django 4.2.7 on 2023-12-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='solutions'),
        ),
    ]
