# Generated by Django 4.2.7 on 2023-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_category_slug_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
