# Generated by Django 4.2.7 on 2023-12-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_site_slug_alter_site_name'),
        ('solutions', '0007_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solutions.solution')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.site')),
            ],
            bases=('solutions.solution',),
        ),
    ]
