# Generated by Django 4.2.7 on 2023-12-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_secondry_sites_user_ssites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0013_alter_solution_visible_alter_solution_visible_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.category'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site'),
        ),
    ]
