# Generated by Django 4.2.7 on 2024-01-21 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
