# Generated by Django 4.2.7 on 2024-01-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemgmt', '0003_workrecord_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='length_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
