# Generated by Django 4.2.7 on 2023-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Algorithms', 'Algorithms'), ('Graph', 'Graph')], max_length=15)),
                ('teachers_teaching', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Bad', 'Bad'), ('Very Bad', 'Very Bad')], max_length=15)),
                ('teachers_availability', models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Bad', 'Bad'), ('Very Bad', 'Very Bad')], max_length=15)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('description4', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
