# Generated by Django 4.2.7 on 2023-12-05 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_site_user_contact_user_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.site'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
