# Generated by Django 4.2.7 on 2023-12-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_alter_solution_file'),
        ('ticket', '0004_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solutions.solution'),
        ),
    ]
