# Generated by Django 4.2.7 on 2023-12-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_number',
            new_name='number',
        ),
    ]
