# Generated by Django 4.2.7 on 2023-12-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_secondry_sites_user_ssites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0014_alter_solution_category_alter_solution_owner_and_more'),
        ('ticket', '0007_alter_ticket_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.solution'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
